apiVersion: v1
kind: Service
metadata:
  name: mypodinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: port-1
      nodePort: 30410
      port: 9898
      protocol: TCP
      targetPort: 9898
